FROM golang:1.17-alpine

RUN apk add --update git alpine-sdk bash
RUN go install github.com/tebeka/go2xunit@latest && \
    go install golang.org/x/lint/golint@latest && \
    go install github.com/t-yuki/gocover-cobertura@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest && \
    go install github.com/golang/mock/gomock@latest
WORKDIR /app

ENV GOFLAGS -mod=vendor
ADD . /app
RUN make generate_swagger
