FROM golang:1.17-alpine

RUN apk add --update git alpine-sdk bash
RUN go install github.com/tebeka/go2xunit && \
    go install golang.org/x/lint/golint && \
    go install github.com/t-yuki/gocover-cobertura && \
    go install github.com/swaggo/swag/cmd/swag && \
    go install github.com/golang/mock/gomock
WORKDIR /app

ENV GOFLAGS -mod=vendor
ADD . /app
RUN make generate_swagger
