---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-manager
  namespace: <<please set>>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: update-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: update-manager
  namespace: <<please set>>
